import { Link } from "react-router-dom";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Privacy = () => {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 pt-24 pb-12 max-w-4xl">
        <div className="prose prose-lg max-w-none">
          <h1 className="text-4xl font-bold text-foreground mb-8">Privacy Policy</h1>
          <p className="text-muted-foreground italic mb-8">Last updated: July 24, 2025</p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">1. Introduction</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Welcome to Costras ("we", "us", "our"). We are committed to protecting your privacy and ensuring the security of your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website https://www.costras.com, use our Chrome extension, or interact with our services.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              By using our services, you agree to the collection and use of information in accordance with this policy.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">2. Information We Collect</h2>
            
            <div className="mb-4">
              <h3 className="text-xl font-medium text-foreground mb-2">a. Account Information</h3>
              <ul className="list-disc list-inside text-muted-foreground space-y-1">
                <li>Email address (collected via Supabase authentication or Google OAuth)</li>
                <li>Name (if provided)</li>
                <li>User ID (generated by our authentication system)</li>
              </ul>
            </div>

            <div className="mb-4">
              <h3 className="text-xl font-medium text-foreground mb-2">b. Usage Data</h3>
              <ul className="list-disc list-inside text-muted-foreground space-y-1">
                <li>Actions performed within the Costras platform (e.g., bot activation, dashboard usage)</li>
                <li>Technical logs for debugging and service improvement</li>
                <li>Analytics data (e.g., page views, feature usage, device/browser type)</li>
              </ul>
            </div>

            <div className="mb-4">
              <h3 className="text-xl font-medium text-foreground mb-2">c. Twitter Authentication Data</h3>
              <ul className="list-disc list-inside text-muted-foreground space-y-1">
                <li>Twitter session cookies (collected via the Chrome extension, only with your explicit consent, and transmitted securely to our backend for bot operation)</li>
              </ul>
            </div>

            <div className="mb-4">
              <h3 className="text-xl font-medium text-foreground mb-2">d. Device and Technical Data</h3>
              <ul className="list-disc list-inside text-muted-foreground space-y-1">
                <li>Browser type and version</li>
                <li>Operating system</li>
                <li>IP address (for security and fraud prevention)</li>
                <li>Device identifiers (for extension functionality)</li>
              </ul>
            </div>

            <div className="mb-4">
              <h3 className="text-xl font-medium text-foreground mb-2">e. Cookies and Tracking Technologies</h3>
              <ul className="list-disc list-inside text-muted-foreground space-y-1">
                <li>We use strictly necessary cookies for authentication and session management.</li>
                <li>We do not use cookies for advertising or third-party tracking.</li>
              </ul>
            </div>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">3. How We Use Your Information</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">We use your information for the following purposes:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>To provide, operate, and maintain our services</li>
              <li>To authenticate users and manage accounts</li>
              <li>To enable secure connection between your Twitter account and Costras</li>
              <li>To operate the Twitter automation bot on your behalf, only after your explicit consent</li>
              <li>To communicate with you regarding service updates, security alerts, and support</li>
              <li>To monitor and improve our services, including debugging and analytics (aggregated and anonymized)</li>
              <li>To comply with legal obligations and enforce our Terms of Service</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">4. How We Share Your Information</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              We do not sell or rent your personal information to third parties. We may share your information only in the following circumstances:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li><strong>Service Providers:</strong> With trusted vendors (e.g., hosting providers like Vercel, authentication providers like Supabase, analytics providers) who process data on our behalf, under strict confidentiality agreements.</li>
              <li><strong>Legal Compliance:</strong> If required by law, regulation, or legal process, or to protect the rights, property, or safety of Costras, our users, or others.</li>
              <li><strong>Business Transfers:</strong> In the event of a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction, subject to this Privacy Policy.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">5. Data Security</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              We take data security seriously and implement industry-standard measures to protect your information, including:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Encryption of data in transit (HTTPS) and at rest</li>
              <li>Secure storage of Twitter authentication data (never stored in plain text)</li>
              <li>Access controls and authentication for all internal systems</li>
              <li>Regular security reviews and vulnerability assessments</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">6. Data Retention</h2>
            <p className="text-muted-foreground leading-relaxed">
              We retain your personal information only as long as necessary to provide our services, comply with legal obligations, resolve disputes, and enforce our agreements. You may request deletion of your account and associated data at any time.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">7. Your Rights</h2>
            <p className="text-muted-foreground leading-relaxed mb-4">
              Depending on your jurisdiction, you may have the following rights regarding your personal data:
            </p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2">
              <li>Access to the personal information we hold about you</li>
              <li>Correction of inaccurate or incomplete information</li>
              <li>Deletion of your personal data ("right to be forgotten")</li>
              <li>Restriction or objection to certain processing activities</li>
              <li>Data portability</li>
            </ul>
            <p className="text-muted-foreground leading-relaxed mt-4">
              To exercise any of these rights, please visit our{" "}
              <Link to="/contact" className="text-primary hover:underline">
                Contact page
              </Link>{" "}
              and submit your request. We will respond promptly in accordance with applicable law.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">8. Children's Privacy</h2>
            <p className="text-muted-foreground leading-relaxed">
              Our services are not intended for children under the age of 16. We do not knowingly collect personal information from children. If you believe a child has provided us with personal data, please contact us immediately via our{" "}
              <Link to="/contact" className="text-primary hover:underline">
                Contact page
              </Link>.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">9. International Data Transfers</h2>
            <p className="text-muted-foreground leading-relaxed">
              Your information may be processed and stored in countries outside your country of residence, including the United States and the European Union. We ensure that such transfers comply with applicable data protection laws and that your data remains protected.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">10. Changes to This Privacy Policy</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new policy on our website and updating the "Last updated" date. Your continued use of our services after such changes constitutes your acceptance of the revised policy.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">11. Contact Us</h2>
            <p className="text-muted-foreground leading-relaxed">
              If you have any questions, concerns, or requests regarding this Privacy Policy or your personal data, please visit our{" "}
              <Link to="/contact" className="text-primary hover:underline">
                Contact page
              </Link>. We are committed to addressing your inquiries promptly and transparently.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Privacy;