// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjsuwthvozuzabktkcxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqc3V3dGh2b3p1emFia3RrY3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDI5OTQsImV4cCI6MjA2ODU3ODk5NH0.pPe3MMWw-KBLLLSwxvjVgFz9LLoJRYByO8BazltpMXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});